const titulo_del_juego = "VERTEBRADOS";

const preguntas = [
  { pregunta: "DEFINICIÓN DE VERTEBRADOS", respuesta: "Seres más complejos y evolucionados. Tienen columna vertebral (en cuyo interior está la médula espinal) y esqueleto interno de hueso o cartílago. Cuerpo dividido en cabeza, tronco y cola. Simetría bilateral. Extremidades articuladas.Tienen piel", palabrasclave: "columna,vertebral,médula,esqueleto,cabeza,tronco,cola,bilateral,extremidades" },
  { pregunta: "FUNCIONES VITALES DE LOS VERTEBRADOS: NUTRICIÓN", respuesta: "Aparato digestivo complejo con glándulas. Aparato excretor complejo cuyo órgano principal son los riñones. Aparato circulatorio cerrado (sangre dentro de los vasos). Aparato respiratorio por branquias, pulmones o piel.", palabrasclave: "digestivo,excretor,riñones,circulatorio,respiratorio,branquias,pulmones" },
  { pregunta: "FUNCIONES VITALES DE LOS VERTEBRADOS: RELACIÓN", respuesta: "Sistema nervioso y sensorial muy complejo, formado por el encéfalo, la médula espinal y los nervios.", palabrasclave: "nervioso,encéfalo,médula,nervios" },
  { pregunta: "FUNCIONES VITALES DE LOS VERTEBRADOS: REPRODUCCIÓN", respuesta: "Absolutamente todos se reproducen por reproducción sexual. La mayoría tienen desarrollo directo, aunque algunos hacen metamorfosis (concretamente los anfibios). Según donde se desarrolla el embrión pueden ser: ovíparos (en un huevo), vivíparos (en el vientre materno) u ovovivíparos (en un huevo dentro del vientre del progenitor).", palabrasclave: "sexual,directo,metamorfosis,ovíparos,vivíparos,ovovivíparos" },
  { pregunta: "PLACENTA", respuesta: "Órgano que nutre al embrión dentro del útero, a través del cordón umbilical, en los mamíferos placentarios.", palabrasclave: "nutre,embrión,útero,cordón,umbilical,mamíferos,placentarios" },
  { pregunta: "METAMORFOSIS", respuesta: "Es un cambio radical entre la etapa infantil de un animal (larva o renacuajo) y el adulto. Es propia de los anfibios. La larva suele tener branquias y sin patas, y el adulto tiene pulmones y patas.", palabrasclave: "cambio,larva,renacuajo,adulto,anfibios,branquias,patas,pulmones" },
  { pregunta: "PECES ÓSEOS", respuesta: "Es lo mismo que decir Osteíctios.", palabrasclave: "osteíctios" },
  { pregunta: "PECES CARTILAGINOSOS", respuesta: "Es lo mismo que decir Condrictios.", palabrasclave: "condrictios" },
  { pregunta: "FECUNDACIÓN INTERNA Y EXTERNA", respuesta: "La fecundación interna es cuando el espermatozoide fecunda el óvulo dentro del cuerpo de la hembra. La fecundación externa es cuando lo hace fuera del cuerpo, en el agua.", palabrasclave: "espermatozoide,óvulo,hembra,agua" },
  { pregunta: "CARACTERÍSTICAS DE LOS SERES HUMANOS", respuesta: "Somos mamíferos placentarios con características especiales: gran cerebro (nos proporciona un lenguaje complejo), pulgar oponible (agarramos y manipulamos objetos), bípedos (caminamos erguidos) y poco pelo (sólo en algunas zonas).", palabrasclave: "mamíferos,cerebro,lenguaje,pulgar,oponible,bípedos,erguidos,pelo" },
  { pregunta: "ECTOTERMOS", respuesta: "Es lo mismo que decir POIQUILOTERMOS, o animales de sangre fría. No regulan su propia temperatura, que depende de la temperatura exterior. A veces hibernan. Son ectotermos los peces, anfibios y reptiles.", palabrasclave: "poiquilotermos,fría,temperatura,hibernan,peces,anfibios,reptiles" },
  { pregunta: "ENDOTERMOS", respuesta: "Es lo mismo que decir HOMEOTERMOS, o animales de sangre caliente. Su temperatura corporal permanece constante, independientemente de la temperatura exterior. Son endotermos las aves y los mamíferos.", palabrasclave: "homeotermos,caliente,constante,aves,mamíferos" }
];
